-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 15:53:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id_user` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL DEFAULT 'Pending',
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Training` (
  `id_training` INT UNSIGNED NOT NULL,
  `info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_training`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `id_user` INT UNSIGNED NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `id_training` INT UNSIGNED NULL,
  PRIMARY KEY (`id_user`),
  INDEX `id_training_idx` (`id_training` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_training`
    FOREIGN KEY (`id_training`)
    REFERENCES `mydb`.`Training` (`id_training`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `id_Team` INT NOT NULL,
  `info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Team`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player_has_Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player_has_Team` (
  `Player_id_user` INT UNSIGNED NOT NULL,
  `Team_id_Team` INT NOT NULL,
  PRIMARY KEY (`Player_id_user`, `Team_id_Team`),
  INDEX `fk_Player_has_Team_Team1_idx` (`Team_id_Team` ASC) VISIBLE,
  INDEX `fk_Player_has_Team_Player1_idx` (`Player_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Player_has_Team_Player1`
    FOREIGN KEY (`Player_id_user`)
    REFERENCES `mydb`.`Player` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_has_Team_Team1`
    FOREIGN KEY (`Team_id_Team`)
    REFERENCES `mydb`.`Team` (`id_Team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
