-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 10:30:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sportup-java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportup-java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportup-java` DEFAULT CHARACTER SET utf8 ;
USE `sportup-java` ;

-- -----------------------------------------------------
-- Table `sportup-java`.`training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportup-java`.`training` (
  `id_training` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_training`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportup-java`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportup-java`.`user` (
  `id_user` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL DEFAULT 'Pending',
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportup-java`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportup-java`.`player` (
  `id_user` INT(10) UNSIGNED NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'Pending',
  `id_training` INT(10) UNSIGNED NULL DEFAULT NULL,
  `info` VARCHAR(45) NULL DEFAULT 'No Info',
  PRIMARY KEY (`id_user`),
  INDEX `fk_Player_Training1_idx` (`id_training` ASC) VISIBLE,
  INDEX `fk_Player_User1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Player_Training1`
    FOREIGN KEY (`id_training`)
    REFERENCES `sportup-java`.`training` (`id_training`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Player_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sportup-java`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportup-java`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportup-java`.`team` (
  `id_team` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_team`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportup-java`.`playerteam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportup-java`.`playerteam` (
  `id_user` INT(10) UNSIGNED NOT NULL,
  `id_team` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_Player_has_Team_Team1_idx` (`id_team` ASC) VISIBLE,
  INDEX `fk_Player_has_Team_Player1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Player_has_Team_Player1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sportup-java`.`player` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Player_has_Team_Team1`
    FOREIGN KEY (`id_team`)
    REFERENCES `sportup-java`.`team` (`id_team`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
